#! /usr/bin/env python

import sys
import commands
import os.path

print sys.prefix
folder = os.path.split(commands.getoutput('find %s -name "libpython*"' % sys.prefix).splitlines()[0])[0]
print folder




